name: Plesk Installation Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-installation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Plesk CLI
        run: |
          sudo apt update
          sudo apt install -y curl expect
          curl https://installer.plesk.com/plesk-installer | sudo bash

      - name: Verify Plesk installation
        run: plesk version

      - name: Run installation script
        run: |
          echo "Running installation script..."
          expect -c '
            spawn plesk installer --all-versions --web-interface-repository-url none
            expect {
              "Would you like to help Plesk make better products by sending information" {
                send "N\r"
                exp_continue
              }
              "Type Y for yes or N for no" {
                send "N\r"
                exp_continue
              }
              "Select an action" {
                send "install\r"
                exp_continue
              }
              eof
            }
          '
