name: Plesk Installation Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-installation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install necessary packages
        run: |
          sudo apt update
          sudo apt install -y curl expect zip unzip

      - name: Install Plesk CLI
        run: |
          curl https://installer.plesk.com/plesk-installer | sudo bash
          sudo plesk installer --version || echo "Plesk CLI installation failed!"

      - name: Verify Plesk installation
        run: |
          plesk version || echo "Plesk is not installed or not accessible."

      - name: Download humhub-extension.php
        run: |
          mkdir -p install
          curl -o install/humhub-extension.php

      - name: Set permissions for humhub-extension.php
        run: |
          chmod +x install/humhub-extension.php

      - name: Run installation script
        run: |
          echo "Running installation script..."
          expect -c '
            spawn plesk installer --all-versions --web-interface-repository-url none
            expect {
              "Would you like to help Plesk make better products by sending information" {
                send "N\r"
                exp_continue
              }
              "Type Y for yes or N for no" {
                send "N\r"
                exp_continue
              }
              "Select an action" {
                send "install\r"
                exp_continue
              }
              eof
            }
          '
