name: Plesk Installation Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-installation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Plesk CLI
        run: |
          sudo apt update
          sudo apt install -y curl
          curl https://installer.plesk.com/plesk-installer | sudo DEBIAN_FRONTEND=noninteractive bash

      - name: Verify Plesk installation
        run: plesk version

      - name: Navigate to install folder
        run: cd install

      - name: Run installation script
        run: |
          echo "Running installation script..."
          php humhub-extension.php install
