name: Plesk Installation and Extension Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-installation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install necessary packages
        run: |
          sudo apt update
          sudo apt install -y wget expect

      - name: Download Plesk Installer
        run: |
          wget -O - http://installer.plesk.com/one-click-installer | sudo bash

      - name: Verify Plesk installation
        run: |
          plesk version || echo "Plesk is not installed or not accessible."

      - name: Download humhub-extension.php
        run: |
          mkdir -p install
          wget -O install/humhub-extension.php

      - name: Upload extension to Plesk
        run: |
          plesk ext repository --add https://github.com/GreenMeteor/humhub-extension.git
          plesk ext install humhub-extension || echo "Extension installation failed!"

      - name: Verify extension installation
        run: |
          plesk ext list | grep humhub-extension || echo "Extension is not installed."

      - name: Verify extension functionality
        run: |
          # Add commands to test the functionality of the extension here
